app:
  inventoryPath: examples/inventory.yaml
  archiveDir: test_archive

  assetsDistribution:
    dir:
      path: test_archive

  agentDistribution:
    dir:
      path: dist

  logsStorage:
    dir:
      path: test_logs
#  hooks:
#    report:
#      if: status == "failure"
#      http:
#        url: https://webhook.site/xxx
#        data: !!json ${{ getVars() | toJson }}
